= Multiple Branches on GitHub Pages

In this chapter, we attempt to produce two versions of the same chapter index page, one with links to other quick courses, another without, that share the same content for all other chapters and sections, and all live in the same git repository.

The two versions are in different branches: `main` and `nolinks`. If differences between these branches are minimal (as in our current use case of not displaying links in a single page) it should be manageable.

This page should display in the `nolinks` branch.

== Red Hat Device Edge Quick Courses

NOTE: If this experiment works, you should see a sentence that apologizes it cannot provide any links.

All Red Hat Device Edge quick courses use a ROLE classroom, which requires a Red Hat Learning Subscription. If you are here, it seems that you do not have a learning subscription.

All other chapters and sections are, for now, unchanged from the starter template, but they may be changed in the future, if we use this git repository for further experiments.