= How It Works

Standard Antora web sites are in a directory named aftger the github project (or whatever the top level name of it for Antora xrefs), for example `playground/1/` and it generates an index.html page on the root directory.

That gives us lots of freedom to add additional subdirectories for banches, and them you just have to refer to those directories explicity in your URLs, and they won't conflict with the URLs from the main branch or default GitHub pages.

You change the GitHub actions workflow in `.github/workflows/main.yml` to:

* Monitor branches other than `main`.
* Geenerate other branches in a subdirectory.
* Not delete preexisting files inside the `gh-pages` branch.

If you're modifying an existing repo, you may need to configure the action to delete files, and then change the action to not delete then anymore. Or just manually clean the `gh-pages` branch.

NOTE: I tested manual clean up. The push to `gh-pages` fires the GitHub action but doesn't mess up with the published pages.

Changed this section, just to test that, as I update main, I can sync (merge) those changes with nolinks, and still keep the changes from nolinks.

== Caveats

If you must change the files that are different in nolinks, after the merge you have to re-apply the edits that make the nolinks branch different from main.

Keeping old files on the `gh-pages` branch may mislead you into thinking changes were NOT published, if you change file names and your Antora book structure, and then refresh a web browser that was on a page with the old name: the old page is still there, even if unreachable by Antora navigation.

An alternative would be to change the GitHub page action to always push and buil all branches, cleaning and regenerating the `gh-pages` at every run. This is possible, just more work (and a longer running action).

True, this is more of a _hack_ on GitHub Actions than using Antora's features.